jobs:
  test-js:
    name: Test JavaScript
    uses: ./.github/workflows/job-jest.yml
  build-css:
    name: Build CSS
    needs:
      - test-js
    uses: ./.github/workflows/job-sass.yml
  build-js:
    name: Build JavaScript
    needs:
      - test-js
    uses: ./.github/workflows/job-webpack.yml
on:
  push:
    branches:
      - dev
