jobs:
  build-css:
    name: Build CSS
    uses: ./.github/workflows/job-sass.yml
    with:
      artifact: true
  build-js:
    name: Build JavaScript
    uses: ./.github/workflows/job-webpack.yml
    with:
      artifact: true
  deploy:
    environment:
      name: github-pages
      url: https://password-generator.ilyabakhlin.com/
    name: Deploy
    needs:
      - build-css
      - build-js
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download CSS
        uses: actions/download-artifact@v3
        with:
          name: css
          path: ./public/css/
      - name: Download JavaScript
        uses: actions/download-artifact@v3
        with:
          name: js
          path: ./public/js/
      - name: Setup pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
on:
  push:
    branches:
      - pro
permissions:
  contents: read
  id-token: write
  pages: write
