jobs:
  build-css:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build CSS
        uses: ./.github/workflows/build-css.yml
on:
  push:
    branches:
      - dev
