jobs:
  css:
    container: quorrax/sass:latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Transpile CSS
        run: sass --no-source-map --style compressed ./source/Sass/:./public/css/
      - name: Artifact CSS
        if: ${{ inputs.artifact }}
        uses: actions/upload-artifact@v3
        with:
          name: css
          path: ./public/css/
          retention-days: 8
on:
  workflow_call:
    inputs:
      artifact:
        default: false
        required: false
        type: boolean
