jobs:
  build-css:
    runs-on: ubuntu-latest
    steps:
      - name: Install Sass
        run: curl -Ls https://github.com/sass/dart-sass/releases/download/1.54.3/dart-sass-1.54.3-linux-x64.tar.gz | tar -C /usr/local/bin/ --strip-components 1 -v -x -z dart-sass/sass && chmod -v 755 /usr/local/bin/sass
      - name: Checkout
        uses: actions/checkout@v3
      - name: Sass
        run: sass --no-source-map --style compressed ./source/Sass/:./public/css/
      - name: Artifact
        uses: actions/upload-artifact@v3
        with:
          name: css
          path: ./public/css/
          retention-days: 8
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs:
      - build-css
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download CSS
        uses: actions/download-artifact@v3
        with:
          name: css
          path: ./public/css/
      - name: List the directory's content
        run: pwd && ls -ahl ./ && id && echo ${HOME}
      - name: Setup pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./public/"
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
on:
  push:
    branches:
      - "pro"
      - "dev"
permissions:
  contents: read
  id-token: write
  pages: write
