jobs:
  build-css:
    uses: ./.github/workflows/build-css.yml
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs:
      - build-css
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download CSS
        uses: actions/download-artifact@v3
        with:
          name: css
          path: ./public/css/
      - name: List the directory's content
        run: pwd && ls -ahl ./ && id && echo ${HOME}
      - name: Setup pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public/
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
on:
  push:
    branches:
      - pro
permissions:
  contents: read
  id-token: write
  pages: write
